services:
  db:
    image: postgres:16-alpine
    ports: ["5432:5432"]
    environment:
      POSTGRES_DB: sinecta_cotizador
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes: [ "pgdata:/var/lib/postgresql/data" ]
  db_test:
    image: postgres:16-alpine
    ports: ["5433:5432"]
    environment:
      POSTGRES_DB: sinecta_cotizador_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    tmpfs:
      - /var/lib/postgresql/data
volumes:
  pgdata:
